# Template: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package using Pip

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # --- INSTALLATIONS ---
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Load cache of pip dependencies
      uses: actions/cache@master
      id: cache_requirements
      with:
        path: ${{ env.pythonLocation }}/lib/python3.9/site-packages/*
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install pip dev dependencies + package if needed
      if: steps.cache_requirements.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]

    - name: Install package if needed
      if: steps.cache_requirements.outputs.cache-hit == 'true'
      run: |
        python -m pip install -e . --no-dependencies
  
    - name: Load cache of external code
      uses: actions/cache@master
      id: cache_external
      with:
        path: /home/runner/aac-metrics-cache/*
        key: ${{ runner.os }}-${{ hashFiles('install_spice.sh') }}
        restore-keys: |
          ${{ runner.os }}-

    # --- TESTS ---
    - name: Lint with flake8
      run: |
        python -m flake8 --config .flake8 --exit-zero --show-source --statistics src

    - name: Check format with Black
      run: |
        python -m black --check --diff src
  
    - name: Install external code if needed
      if: steps.cache_external.outputs.cache-hit != 'true'
      run: |
        aac-metrics-download
      
    - name: Print install info
      run: |
        aac-metrics-info
  
    - name: Test with pytest
      run: |
        python -m pytest -v
