# Template: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package using Pip

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  CACHE_NUMBER: 0  # increase to reset cache manually
  AAC_METRICS_TMP_PATH: '/tmp'

# Cancel workflow if a new push occurs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
        python-version: ["3.9"]
        java-version: ["11"]

    steps:
    # --- INSTALLATIONS ---
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install uv and set Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
        cache-dependency-glob: "pyproject.toml"

    - name: Set up Java ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}
        java-package: jre

    - name: Install the project
      run: |
        uv sync --all-extras --dev

    - name: Load cache of external code and data
      uses: actions/cache@master
      id: cache_external
      with:
        path: /home/runner/.cache/aac-metrics/*
        key: ${{ runner.os }}-${{ hashFiles('src/aac_metrics/download.py') }}
        restore-keys: |
          ${{ runner.os }}-

    # --- TESTS ---
    - name: Print install info
      run: |
        uv run aac-metrics-info

    - name: Print Java version
      run: |
        uv run java -version

    - name: Check format with Ruff
      run: |
        uv run ruff check

    - name: Install external code if needed
      if: steps.cache_external.outputs.cache-hit != 'true'
      run: |
        uv run aac-metrics-download

    - name: Test with coverage + pytest
      run: |
        uv run coverage run -m pytest -v

    - name: Show coverage results
      run: |
        uv run coverage report -m
